type CurrencyMap = {
    [key: string]: {
        abbreviation: string
        currency: string
        rate: number
    }
}

export default {
    Afghanistan: {
        abbreviation: 'AF',
        currency: 'AFN',
        rate: 86.693270950873,
    },
    Albania: {
        abbreviation: 'AL',
        currency: 'ALL',
        rate: 107.97972625548,
    },
    Algeria: {
        abbreviation: 'DZ',
        currency: 'DZD',
        rate: 137.69234653675,
    },
    'American Samoa': {
        abbreviation: 'AS',
        currency: 'USD',
        rate: 1,
    },
    Andorra: {
        abbreviation: 'AD',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Angola: {
        abbreviation: 'AO',
        currency: 'AOA',
        rate: 512.79069767442,
    },
    Anguilla: {
        abbreviation: 'AI',
        currency: 'XCD',
        rate: 2.713512183116,
    },
    Antarctica: {
        abbreviation: 'AQ',
        currency: 'USD',
        rate: 1,
    },
    'Antigua And Barbuda': {
        abbreviation: 'AG',
        currency: 'XCD',
        rate: 2.713512183116,
    },
    Argentina: {
        abbreviation: 'AR',
        currency: 'ARS',
        rate: 172.16240868761,
    },
    Armenia: {
        abbreviation: 'AM',
        currency: 'AMD',
        rate: 395.37082248056,
    },
    Aruba: {
        abbreviation: 'AW',
        currency: 'AWG',
        rate: 1.8115346697338,
    },
    'Ascension Island': {
        abbreviation: 'AC',
        currency: 'SHP',
        rate: 1,
    },
    Australia: {
        abbreviation: 'AU',
        currency: 'AUD',
        rate: 1.4633241803307,
    },
    Austria: {
        abbreviation: 'AT',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Azerbaijan: {
        abbreviation: 'AZN',
        currency: 'USD',
        rate: 1,
    },
    Bahamas: {
        abbreviation: 'BS',
        currency: 'BSD',
        rate: 1.0028881359016,
    },
    Bahrain: {
        abbreviation: 'BH',
        currency: 'BHD',
        rate: 0.37632575307886,
    },
    Bangladesh: {
        abbreviation: 'BD',
        currency: 'BDT',
        rate: 103.4571737866,
    },
    Barbados: {
        abbreviation: 'BB',
        currency: 'BBD',
        rate: 2.0210815765353,
    },
    Belarus: {
        abbreviation: 'BY',
        currency: 'BYR',
        rate: 1,
    },
    Belgium: {
        abbreviation: 'BE',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Belize: {
        abbreviation: 'BZ',
        currency: 'BZD',
        rate: 2.0176602461454,
    },
    Benin: {
        abbreviation: 'BJ',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    Bermuda: {
        abbreviation: 'BM',
        currency: 'BMD',
        rate: 1,
    },
    Bhutan: {
        abbreviation: 'BT',
        currency: 'BTN',
        rate: 1,
    },
    Bolivia: {
        abbreviation: 'BO',
        currency: 'BOB',
        rate: 6.9008011962852,
    },
    'Bosnia And Herzegowina': {
        abbreviation: 'BA',
        currency: 'BAM',
        rate: 1.8440309429228,
    },
    Botswana: {
        abbreviation: 'BW',
        currency: 'BWP',
        rate: 12.84965034965,
    },
    'Bouvet Island': {
        abbreviation: 'BV',
        currency: 'NOK',
        rate: 9.7560184284025,
    },
    Brazil: {
        abbreviation: 'BR',
        currency: 'BRL',
        rate: 5.310837859965,
    },
    'British Indian Ocean Territory': {
        abbreviation: 'IO',
        currency: 'USD',
        rate: 1,
    },
    'Brunei Darussalam': {
        abbreviation: 'BN',
        currency: 'BND',
        rate: 1.3488713525418,
    },
    Bulgaria: {
        abbreviation: 'BG',
        currency: 'BGN',
        rate: 1.8389119046299,
    },
    'Burkina Faso': {
        abbreviation: 'BF',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    Burundi: {
        abbreviation: 'BI',
        currency: 'BIF',
        rate: 2073.3427362483,
    },
    Cambodia: {
        abbreviation: 'KH',
        currency: 'KHR',
        rate: 4113.8059701493,
    },
    Cameroon: {
        abbreviation: 'CM',
        currency: 'XAF',
        rate: 618.32234193319,
    },
    Canada: {
        abbreviation: 'CA',
        currency: 'CAD',
        rate: 1.3561286998546,
    },
    'Cape Verde': {
        abbreviation: 'CV',
        currency: 'CVE',
        rate: 104.25531914894,
    },
    'Cayman Islands': {
        abbreviation: 'KY',
        currency: 'KYD',
        rate: 1,
    },
    'Central African Republic': {
        abbreviation: 'CF',
        currency: 'XAF',
        rate: 618.32234193319,
    },
    Chad: {
        abbreviation: 'TD',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    Chile: {
        abbreviation: 'CL',
        currency: 'CLP',
        rate: 870.87776545454,
    },
    China: {
        abbreviation: 'CN',
        currency: 'CNY',
        rate: 6.957466502114,
    },
    'Christmas Island': {
        abbreviation: 'CX',
        currency: 'AUD',
        rate: 1.4633241803307,
    },
    'Cocos (Keeling) Islands': {
        abbreviation: 'CC',
        currency: 'USD',
        rate: 1,
    },
    Colombia: {
        abbreviation: 'CO',
        currency: 'COP',
        rate: 4782.3851823852,
    },
    Comoros: {
        abbreviation: 'KM',
        currency: 'KMF',
        rate: 463.43001261034,
    },
    Congo: {
        abbreviation: 'CG',
        currency: 'CDF',
        rate: 2056.9029850746,
    },
    "Congo, Democratic People's Republic": {
        abbreviation: 'CD',
        currency: 'CDF',
        rate: 2056.9029850746,
    },
    'Cook Islands': {
        abbreviation: 'CK',
        currency: 'NZD',
        rate: 1.5546663275345,
    },
    'Costa Rica': {
        abbreviation: 'CR',
        currency: 'CRC',
        rate: 595.52808109172,
    },
    "Cote d'Ivoire": {
        abbreviation: 'CI',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    'Croatia (local name: Hrvatska)': {
        abbreviation: 'HR',
        currency: 'HRK',
        rate: 7.0878460890463,
    },
    Cuba: {
        abbreviation: 'CU',
        currency: 'CUP',
        rate: 1.0028881359016,
    },
    Cyprus: {
        abbreviation: 'CY',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'Czech Republic': {
        abbreviation: 'CZ',
        currency: 'CZK',
        rate: 22.824838281275,
    },
    Denmark: {
        abbreviation: 'DK',
        currency: 'DKK',
        rate: 6.9955319421685,
    },
    Djibouti: {
        abbreviation: 'DJ',
        currency: 'DJF',
        rate: 178.19621787619,
    },
    Dominica: {
        abbreviation: 'DM',
        currency: 'XCD',
        rate: 2.713512183116,
    },
    'Dominican Republic': {
        abbreviation: 'DO',
        currency: 'DOP',
        rate: 54.940564353031,
    },
    'East Timor': {
        abbreviation: 'TP',
        currency: 'USD',
        rate: 1,
    },
    Ecuador: {
        abbreviation: 'EC',
        currency: 'USD',
        rate: 1,
    },
    Egypt: {
        abbreviation: 'EG',
        currency: 'EGP',
        rate: 24.695910161294,
    },
    'El Salvador': {
        abbreviation: 'SV',
        currency: 'USD',
        rate: 1,
    },
    'Equatorial Guinea': {
        abbreviation: 'GQ',
        currency: 'XAF',
        rate: 618.32234193319,
    },
    Eritrea: {
        abbreviation: 'ER',
        currency: 'ERN',
        rate: 15.092402464066,
    },
    Estonia: {
        abbreviation: 'EE',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Ethiopia: {
        abbreviation: 'ET',
        currency: 'ETB',
        rate: 53.584447144595,
    },
    'Falkland Islands (Malvinas)': {
        abbreviation: 'FK',
        currency: 'FKP',
        rate: 1,
    },
    'Faroe Islands': {
        abbreviation: 'FO',
        currency: 'DKK',
        rate: 6.9955319421685,
    },
    Fiji: {
        abbreviation: 'FJ',
        currency: 'FJD',
        rate: 2.1863070745129,
    },
    Finland: {
        abbreviation: 'FI',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    France: {
        abbreviation: 'FR',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'French Guiana': {
        abbreviation: 'GF',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'French Polynesia': {
        abbreviation: 'PF',
        currency: 'CFP',
        rate: 1,
    },
    'French Southern Territories': {
        abbreviation: 'TF',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Gabon: {
        abbreviation: 'GA',
        currency: 'XAF',
        rate: 618.32234193319,
    },
    Gambia: {
        abbreviation: 'GM',
        currency: 'GMD',
        rate: 63.271162123385,
    },
    'Georgia (Sakartvelo)': {
        abbreviation: 'GE',
        currency: 'GEL',
        rate: 2.6950489732033,
    },
    Germany: {
        abbreviation: 'DE',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Ghana: {
        abbreviation: 'GH',
        currency: 'GHC',
        rate: 1,
    },
    Gibraltar: {
        abbreviation: 'GI',
        currency: 'GBP',
        rate: 0.80987349303269,
    },
    Greece: {
        abbreviation: 'GR',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Greenland: {
        abbreviation: 'GL',
        currency: 'DKK',
        rate: 6.9955319421685,
    },
    Grenada: {
        abbreviation: 'GD',
        currency: 'XCD',
        rate: 2.713512183116,
    },
    Guadeloupe: {
        abbreviation: 'GP',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Guam: {
        abbreviation: 'GU',
        currency: 'USD',
        rate: 1,
    },
    Guatemala: {
        abbreviation: 'GT',
        currency: 'GTQ',
        rate: 7.8778135048233,
    },
    Guernsey: {
        abbreviation: 'GG',
        currency: 'GBP',
        rate: 0.80987349303269,
    },
    Guinea: {
        abbreviation: 'GN',
        currency: 'GNF',
        rate: 8630.1369863014,
    },
    'Guinea-Bissau': {
        abbreviation: 'GW',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    Guyana: {
        abbreviation: 'GY',
        currency: 'GYD',
        rate: 209.41165297498,
    },
    Haiti: {
        abbreviation: 'HT',
        currency: 'HTG',
        rate: 145.10462644746,
    },
    'Heard And Mc Donald Islands': {
        abbreviation: 'HM',
        currency: 'USD',
        rate: 1,
    },
    Honduras: {
        abbreviation: 'HN',
        currency: 'HNL',
        rate: 24.705882352941,
    },
    'Hong Kong': {
        abbreviation: 'HK',
        currency: 'HKD',
        rate: 7.774350739722,
    },
    Hungary: {
        abbreviation: 'HU',
        currency: 'HUF',
        rate: 381.46206027692,
    },
    Iceland: {
        abbreviation: 'IS',
        currency: 'ISK',
        rate: 141.72595412559,
    },
    India: {
        abbreviation: 'IN',
        currency: 'INR',
        rate: 82.561419467923,
    },
    Indonesia: {
        abbreviation: 'ID',
        currency: 'IDR',
        rate: 15615.382255868,
    },
    'Iran (Islamic Republic Of)': {
        abbreviation: 'IR',
        currency: 'IRR',
        rate: 42000.022970552,
    },
    Iraq: {
        abbreviation: 'IQ',
        currency: 'IQD',
        rate: 1460.3738968751,
    },
    Ireland: {
        abbreviation: 'IE',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'Isle of Man': {
        abbreviation: 'IM',
        currency: 'GBP',
        rate: 0.80987349303269,
    },
    Israel: {
        abbreviation: 'IL',
        currency: 'ILS',
        rate: 3.4104277182034,
    },
    Italy: {
        abbreviation: 'IT',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Jamaica: {
        abbreviation: 'JM',
        currency: 'JMD',
        rate: 153.65853658537,
    },
    Japan: {
        abbreviation: 'JP',
        currency: 'JPY',
        rate: 136.32711904049,
    },
    'Jersey (Island)': {
        abbreviation: 'JE',
        currency: 'GBP',
        rate: 0.80987349303269,
    },
    Jordan: {
        abbreviation: 'JO',
        currency: 'JOD',
        rate: 0.70914755032045,
    },
    Kazakhstan: {
        abbreviation: 'KZ',
        currency: 'KZT',
        rate: 469.33084064492,
    },
    Kenya: {
        abbreviation: 'KE',
        currency: 'KES',
        rate: 122.91655053236,
    },
    Kiribati: {
        abbreviation: 'KI',
        currency: 'AUD',
        rate: 1.4633241803307,
    },
    "Korea, Democratic People's Republic Of": {
        abbreviation: 'KP',
        currency: 'KPW',
        rate: 1,
    },
    'Korea, Republic Of': {
        abbreviation: 'KR',
        currency: 'KRW',
        rate: 1300.9581503095,
    },
    Kuwait: {
        abbreviation: 'KW',
        currency: 'KWD',
        rate: 0.30639622970452,
    },
    Kyrgyzstan: {
        abbreviation: 'KG',
        currency: 'KGS',
        rate: 84.791662895835,
    },
    "Lao People's Democratic Republic": {
        abbreviation: 'LA',
        currency: 'USD',
        rate: 1,
    },
    Latvia: {
        abbreviation: 'LV',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Lebanon: {
        abbreviation: 'LB',
        currency: 'LBP',
        rate: 1519.5110930166,
    },
    Lesotho: {
        abbreviation: 'LS',
        currency: 'ZAR',
        rate: 17.211079354165,
    },
    Liberia: {
        abbreviation: 'LR',
        currency: 'LRD',
        rate: 154.19580419581,
    },
    'Libyan Arab Jamahiriya': {
        abbreviation: 'LY',
        currency: 'LYD',
        rate: 4.8934112661846,
    },
    Liechtenstein: {
        abbreviation: 'LI',
        currency: 'CHF',
        rate: 0.92831293371386,
    },
    Lithuania: {
        abbreviation: 'LT',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Luxembourg: {
        abbreviation: 'LU',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Macau: {
        abbreviation: 'MO',
        currency: 'MOP',
        rate: 8.0210985813024,
    },
    'Macedonia, The Former Yugoslav Republic Of': {
        abbreviation: 'MK',
        currency: 'MKD',
        rate: 57.953873447666,
    },
    Madagascar: {
        abbreviation: 'MG',
        currency: 'MGA',
        rate: 4427.7108433734,
    },
    Malawi: {
        abbreviation: 'MW',
        currency: 'MWK',
        rate: 1027.4930102517,
    },
    Malaysia: {
        abbreviation: 'MY',
        currency: 'MYR',
        rate: 4.4029253792221,
    },
    Maldives: {
        abbreviation: 'MV',
        currency: 'MVR',
        rate: 15.473684210527,
    },
    Mali: {
        abbreviation: 'ML',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    Malta: {
        abbreviation: 'MT',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'Marshall Islands': {
        abbreviation: 'MH',
        currency: 'USD',
        rate: 1,
    },
    Martinique: {
        abbreviation: 'MQ',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Mauritania: {
        abbreviation: 'MR',
        currency: 'MRU',
        rate: 37.724550898204,
    },
    Mauritius: {
        abbreviation: 'MU',
        currency: 'MUR',
        rate: 44.277108433734,
    },
    Mayotte: {
        abbreviation: 'YT',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Mexico: {
        abbreviation: 'MX',
        currency: 'MXN',
        rate: 19.655995295286,
    },
    'Micronesia, Federated States Of': {
        abbreviation: 'FM',
        currency: 'USD',
        rate: 1,
    },
    'Moldova, Republic Of': {
        abbreviation: 'MD',
        currency: 'USD',
        rate: 1,
    },
    Monaco: {
        abbreviation: 'MC',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Mongolia: {
        abbreviation: 'MN',
        currency: 'MNT',
        rate: 3429.2379471229,
    },
    Montserrat: {
        abbreviation: 'MS',
        currency: 'XCD',
        rate: 2.713512183116,
    },
    Morocco: {
        abbreviation: 'MA',
        currency: 'MAD',
        rate: 10.477997678692,
    },
    Mozambique: {
        abbreviation: 'MZ',
        currency: 'MZN',
        rate: 64.192139737991,
    },
    Myanmar: {
        abbreviation: 'MM',
        currency: 'MMK',
        rate: 2102.0019065777,
    },
    Namibia: {
        abbreviation: 'NA',
        currency: 'NAD',
        rate: 17.206398751463,
    },
    Nauru: {
        abbreviation: 'NR',
        currency: 'AUD',
        rate: 1.4633241803307,
    },
    Nepal: {
        abbreviation: 'NP',
        currency: 'NPR',
        rate: 131.97042703236,
    },
    Netherlands: {
        abbreviation: 'NL',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'Netherlands Antilles': {
        abbreviation: 'AN',
        currency: 'ANG',
        rate: 1.7917478884058,
    },
    'New Caledonia': {
        abbreviation: 'NC',
        currency: 'CFP',
        rate: 1,
    },
    'New Zealand': {
        abbreviation: 'NZ',
        currency: 'NZD',
        rate: 1.5546663275345,
    },
    Nicaragua: {
        abbreviation: 'NI',
        currency: 'NIO',
        rate: 36.536868268435,
    },
    Niger: {
        abbreviation: 'NE',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    Nigeria: {
        abbreviation: 'NG',
        currency: 'NGN',
        rate: 446.20217999392,
    },
    Niue: {
        abbreviation: 'NU',
        currency: 'NZD',
        rate: 1.5546663275345,
    },
    'Norfolk Island': {
        abbreviation: 'NF',
        currency: 'AUD',
        rate: 1.4633241803307,
    },
    'Northern Mariana Islands': {
        abbreviation: 'MP',
        currency: 'USD',
        rate: 1,
    },
    Norway: {
        abbreviation: 'NO',
        currency: 'NOK',
        rate: 9.7560184284025,
    },
    Oman: {
        abbreviation: 'OM',
        currency: 'OMR',
        rate: 0.38478282379523,
    },
    Pakistan: {
        abbreviation: 'PK',
        currency: 'PKR',
        rate: 224.71911965588,
    },
    Palau: {
        abbreviation: 'PW',
        currency: 'USD',
        rate: 1,
    },
    'Palestinian Territories': {
        abbreviation: 'PS',
        currency: 'USD',
        rate: 1,
    },
    Panama: {
        abbreviation: 'PA',
        currency: 'PAB',
        rate: 1.0014440679508,
    },
    'Papua New Guinea': {
        abbreviation: 'PG',
        currency: 'PGK',
        rate: 3.5268714011517,
    },
    Paraguay: {
        abbreviation: 'PY',
        currency: 'PYG',
        rate: 7207.5899373231,
    },
    Peru: {
        abbreviation: 'PE',
        currency: 'USD',
        rate: 1,
    },
    Philippines: {
        abbreviation: 'PH',
        currency: 'PHP',
        rate: 55.742646136811,
    },
    Pitcairn: {
        abbreviation: 'PN',
        currency: 'USD',
        rate: 1,
    },
    Poland: {
        abbreviation: 'PL',
        currency: 'PLN',
        rate: 4.4043242444567,
    },
    Portugal: {
        abbreviation: 'PT',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'Puerto Rico': {
        abbreviation: 'PR',
        currency: 'USD',
        rate: 1,
    },
    Qatar: {
        abbreviation: 'QA',
        currency: 'QAR',
        rate: 3.6712568862911,
    },
    Reunion: {
        abbreviation: 'RE',
        currency: 'USD',
        rate: 1,
    },
    Romania: {
        abbreviation: 'RO',
        currency: 'RON',
        rate: 4.6287675715902,
    },
    Russia: {
        abbreviation: 'RU',
        currency: 'RUB',
        rate: 66.532374004313,
    },
    Rwanda: {
        abbreviation: 'RW',
        currency: 'RWF',
        rate: 1062.39460371,
    },
    'Saint Kitts And Nevis': {
        abbreviation: 'KN',
        currency: 'XCD',
        rate: 2.713512183116,
    },
    'Saint Lucia': {
        abbreviation: 'LC',
        currency: 'XCD',
        rate: 2.713512183116,
    },
    'Saint Vincent And The Grenadines': {
        abbreviation: 'VC',
        currency: 'XCD',
        rate: 2.713512183116,
    },
    Samoa: {
        abbreviation: 'WS',
        currency: 'WST',
        rate: 2.7088452088452,
    },
    'San Marino': {
        abbreviation: 'SM',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'Sao Tome And Principe': {
        abbreviation: 'ST',
        currency: 'USD',
        rate: 1,
    },
    'Saudi Arabia': {
        abbreviation: 'SA',
        currency: 'SAR',
        rate: 3.7599157094015,
    },
    Senegal: {
        abbreviation: 'SN',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    'Serbia and Montenegro': {
        abbreviation: 'CS',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Seychelles: {
        abbreviation: 'SC',
        currency: 'SCR',
        rate: 13.160250671442,
    },
    'Sierra Leone': {
        abbreviation: 'SL',
        currency: 'SLL',
        rate: 1,
    },
    Singapore: {
        abbreviation: 'SG',
        currency: 'SGD',
        rate: 1.3484376504985,
    },
    'Slovakia (Slovak Republic)': {
        abbreviation: 'SK',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Slovenia: {
        abbreviation: 'SI',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'Solomon Islands': {
        abbreviation: 'SB',
        currency: 'SBD',
        rate: 8.2630691399663,
    },
    Somalia: {
        abbreviation: 'SO',
        currency: 'SOS',
        rate: 569.03225806454,
    },
    'South Africa': {
        abbreviation: 'ZA',
        currency: 'ZAR',
        rate: 17.211079354165,
    },
    'South Georgia And The South Sandwich Islands': {
        abbreviation: 'GS',
        currency: 'USD',
        rate: 1,
    },
    Spain: {
        abbreviation: 'ES',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    'Sri Lanka': {
        abbreviation: 'LK',
        currency: 'LKR',
        rate: 366.151254542,
    },
    'St. Helena': {
        abbreviation: 'SH',
        currency: 'USD',
        rate: 1,
    },
    'St. Pierre And Miquelon': {
        abbreviation: 'PM',
        currency: 'USD',
        rate: 1,
    },
    Sudan: {
        abbreviation: 'SD',
        currency: 'SDG',
        rate: 565.38461538463,
    },
    Suriname: {
        abbreviation: 'SR',
        currency: 'SRD',
        rate: 32.236842105263,
    },
    'Svalbard And Jan Mayen Islands': {
        abbreviation: 'SJ',
        currency: 'USD',
        rate: 1,
    },
    Swaziland: {
        abbreviation: 'SZ',
        currency: 'SZL',
        rate: 17.206398751463,
    },
    Sweden: {
        abbreviation: 'SE',
        currency: 'SEK',
        rate: 10.218503707556,
    },
    Switzerland: {
        abbreviation: 'CH',
        currency: 'CHF',
        rate: 0.92831293371386,
    },
    'Syrian Arab Republic': {
        abbreviation: 'SY',
        currency: 'SYP',
        rate: 2450,
    },
    Taiwan: {
        abbreviation: 'TW',
        currency: 'TWD',
        rate: 30.577693843321,
    },
    Tajikistan: {
        abbreviation: 'TJ',
        currency: 'TJS',
        rate: 10.168210584934,
    },
    'Tanzania, United Republic Of': {
        abbreviation: 'TZ',
        currency: 'TZS',
        rate: 2335.8050847458,
    },
    Thailand: {
        abbreviation: 'TH',
        currency: 'THB',
        rate: 34.750081992963,
    },
    Togo: {
        abbreviation: 'TG',
        currency: 'XOF',
        rate: 619.73664775096,
    },
    Tokelau: {
        abbreviation: 'TK',
        currency: 'NZD',
        rate: 1.5546663275345,
    },
    Tonga: {
        abbreviation: 'TO',
        currency: 'TOP',
        rate: 2.3844282238443,
    },
    'Trinidad And Tobago': {
        abbreviation: 'TT',
        currency: 'TTD',
        rate: 6.7919297705222,
    },
    Tunisia: {
        abbreviation: 'TN',
        currency: 'TND',
        rate: 3.1444209736503,
    },
    Turkey: {
        abbreviation: 'TR',
        currency: 'TRY',
        rate: 18.641098395819,
    },
    Turkmenistan: {
        abbreviation: 'TM',
        currency: 'TMT',
        rate: 3.499439835242,
    },
    'Turks And Caicos Islands': {
        abbreviation: 'TC',
        currency: 'USD',
        rate: 1,
    },
    Tuvalu: {
        abbreviation: 'TV',
        currency: 'AUD',
        rate: 1.4633241803307,
    },
    'U.S. Minor Outlying Islands': {
        abbreviation: 'UM',
        currency: 'USD',
        rate: 1,
    },
    Uganda: {
        abbreviation: 'UG',
        currency: 'UGX',
        rate: 3702.7707808565,
    },
    Ukraine: {
        abbreviation: 'UA',
        currency: 'UAH',
        rate: 36.720784213571,
    },
    'United Arab Emirates': {
        abbreviation: 'AE',
        currency: 'AED',
        rate: 3.6731498609811,
    },
    'United Kingdom': {
        abbreviation: 'UK',
        currency: 'GBP',
        rate: 0.80987349303269,
    },
    'United States': {
        abbreviation: 'US',
        currency: 'USD',
        rate: 1,
    },
    Uruguay: {
        abbreviation: 'UY',
        currency: 'UYU',
        rate: 38.751256437302,
    },
    Uzbekistan: {
        abbreviation: 'UZ',
        currency: 'UZS',
        rate: 11255.482133136,
    },
    Vanuatu: {
        abbreviation: 'VU',
        currency: 'VUV',
        rate: 121.56797882898,
    },
    'Vatican City State (Holy See)': {
        abbreviation: 'VA',
        currency: 'EUR',
        rate: 0.94103557950651,
    },
    Venezuela: {
        abbreviation: 'VE',
        currency: 'VEB',
        rate: 1,
    },
    VietNam: {
        abbreviation: 'VN',
        currency: 'VND',
        rate: 23579.405733156,
    },
    'Virgin Islands (British)': {
        abbreviation: 'VG',
        currency: 'USD',
        rate: 1,
    },
    'Virgin Islands (U.S.)': {
        abbreviation: 'VI',
        currency: 'USD',
        rate: 1,
    },
    'Wallis And Futuna Islands': {
        abbreviation: 'WF',
        currency: 'XPF',
        rate: 112.36527632685,
    },
    'Western Sahara': {
        abbreviation: 'EH',
        currency: 'MAD',
        rate: 10.477997678692,
    },
    Yemen: {
        abbreviation: 'YE',
        currency: 'YER',
        rate: 250.46856363946,
    },
    Zambia: {
        abbreviation: 'ZM',
        currency: 'ZMW',
        rate: 17.520858164482,
    },
    Zimbabwe: {
        abbreviation: 'ZW',
        currency: 'USD',
        rate: 1,
    },
} as CurrencyMap

export const countryCurrencyMap = {
    AF: 'AFN',
    AL: 'ALL',
    DZ: 'DZD',
    AS: 'USD',
    AD: 'EUR',
    AO: 'AOA',
    AI: 'XCD',
    AQ: 'USD',
    AG: 'XCD',
    AR: 'ARS',
    AM: 'AMD',
    AW: 'AWG',
    AC: 'SHP',
    AU: 'AUD',
    AT: 'EUR',
    AZN: 'USD',
    BS: 'BSD',
    BH: 'BHD',
    BD: 'BDT',
    BB: 'BBD',
    BY: 'BYR',
    BE: 'EUR',
    BZ: 'BZD',
    BJ: 'XOF',
    BM: 'BMD',
    BT: 'BTN',
    BO: 'BOB',
    BA: 'BAM',
    BW: 'BWP',
    BV: 'NOK',
    BR: 'BRL',
    IO: 'USD',
    BN: 'BND',
    BG: 'BGN',
    BF: 'XOF',
    BI: 'BIF',
    KH: 'KHR',
    CM: 'XAF',
    CA: 'CAD',
    CV: 'CVE',
    KY: 'KYD',
    CF: 'XAF',
    TD: 'XOF',
    CL: 'CLP',
    CN: 'CNY',
    CX: 'AUD',
    CC: 'USD',
    CO: 'COP',
    KM: 'KMF',
    CG: 'CDF',
    CD: 'CDF',
    CK: 'NZD',
    CR: 'CRC',
    CI: 'XOF',
    HR: 'HRK',
    CU: 'CUP',
    CY: 'EUR',
    CZ: 'CZK',
    DK: 'DKK',
    DJ: 'DJF',
    DM: 'XCD',
    DO: 'DOP',
    TP: 'USD',
    EC: 'USD',
    EG: 'EGP',
    SV: 'USD',
    GQ: 'XAF',
    ER: 'ERN',
    EE: 'EUR',
    ET: 'ETB',
    FK: 'FKP',
    FO: 'DKK',
    FJ: 'FJD',
    FI: 'EUR',
    FR: 'EUR',
    GF: 'EUR',
    PF: 'CFP',
    TF: 'EUR',
    GA: 'XAF',
    GM: 'GMD',
    GE: 'GEL',
    DE: 'EUR',
    GH: 'GHC',
    GI: 'GBP',
    GR: 'EUR',
    GL: 'DKK',
    GD: 'XCD',
    GP: 'EUR',
    GU: 'USD',
    GT: 'GTQ',
    GG: 'GBP',
    GN: 'GNF',
    GW: 'XOF',
    GY: 'GYD',
    HT: 'HTG',
    HM: 'USD',
    HN: 'HNL',
    HK: 'HKD',
    HU: 'HUF',
    IS: 'ISK',
    IN: 'INR',
    ID: 'IDR',
    IR: 'IRR',
    IQ: 'IQD',
    IE: 'EUR',
    IM: 'GBP',
    IL: 'ILS',
    IT: 'EUR',
    JM: 'JMD',
    JP: 'JPY',
    JE: 'GBP',
    JO: 'JOD',
    KZ: 'KZT',
    KE: 'KES',
    KI: 'AUD',
    KP: 'KPW',
    KR: 'KRW',
    KW: 'KWD',
    KG: 'KGS',
    LA: 'USD',
    LV: 'EUR',
    LB: 'LBP',
    LS: 'ZAR',
    LR: 'LRD',
    LY: 'LYD',
    LI: 'CHF',
    LT: 'EUR',
    LU: 'EUR',
    MO: 'MOP',
    MK: 'MKD',
    MG: 'MGA',
    MW: 'MWK',
    MY: 'MYR',
    MV: 'MVR',
    ML: 'XOF',
    MT: 'EUR',
    MH: 'USD',
    MQ: 'EUR',
    MR: 'MRU',
    MU: 'MUR',
    YT: 'EUR',
    MX: 'MXN',
    FM: 'USD',
    MD: 'USD',
    MC: 'EUR',
    MN: 'MNT',
    MS: 'XCD',
    MA: 'MAD',
    MZ: 'MZN',
    MM: 'MMK',
    NA: 'NAD',
    NR: 'AUD',
    NP: 'NPR',
    NL: 'EUR',
    AN: 'ANG',
    NC: 'CFP',
    NZ: 'NZD',
    NI: 'NIO',
    NE: 'XOF',
    NG: 'NGN',
    NU: 'NZD',
    NF: 'AUD',
    MP: 'USD',
    NO: 'NOK',
    OM: 'OMR',
    PK: 'PKR',
    PW: 'USD',
    PS: 'USD',
    PA: 'PAB',
    PG: 'PGK',
    PY: 'PYG',
    PE: 'USD',
    PH: 'PHP',
    PN: 'USD',
    PL: 'PLN',
    PT: 'EUR',
    PR: 'USD',
    QA: 'QAR',
    RE: 'USD',
    RO: 'RON',
    RU: 'RUB',
    RW: 'RWF',
    KN: 'XCD',
    LC: 'XCD',
    VC: 'XCD',
    WS: 'WST',
    SM: 'EUR',
    ST: 'USD',
    SA: 'SAR',
    SN: 'XOF',
    CS: 'EUR',
    SC: 'SCR',
    SL: 'SLL',
    SG: 'SGD',
    SK: 'EUR',
    SI: 'EUR',
    SB: 'SBD',
    SO: 'SOS',
    ZA: 'ZAR',
    GS: 'USD',
    ES: 'EUR',
    LK: 'LKR',
    SH: 'USD',
    PM: 'USD',
    SD: 'SDG',
    SR: 'SRD',
    SJ: 'USD',
    SZ: 'SZL',
    SE: 'SEK',
    CH: 'CHF',
    SY: 'SYP',
    TW: 'TWD',
    TJ: 'TJS',
    TZ: 'TZS',
    TH: 'THB',
    TG: 'XOF',
    TK: 'NZD',
    TO: 'TOP',
    TT: 'TTD',
    TN: 'TND',
    TR: 'TRY',
    TM: 'TMT',
    TC: 'USD',
    TV: 'AUD',
    UM: 'USD',
    UG: 'UGX',
    UA: 'UAH',
    AE: 'AED',
    UK: 'GBP',
    US: 'USD',
    UY: 'UYU',
    UZ: 'UZS',
    VU: 'VUV',
    VA: 'EUR',
    VE: 'VEB',
    VN: 'VND',
    VG: 'USD',
    VI: 'USD',
    WF: 'XPF',
    EH: 'MAD',
    YE: 'YER',
    ZM: 'ZMW',
    ZW: 'USD',
}

/*Object.keys(currency).forEach((key,i) => {
      const curr = currency[key].currency as string;
      const _rate = (typeof rate[curr.toLowerCase()] == 'undefined' || curr=='USD' )?1: rate[curr.toLowerCase()].rate;
      res[key].rate = _rate
  })*/
