import {SCREEN_HEIGHT, SCREEN_WIDTH} from '@gorhom/bottom-sheet'
import {theme} from 'app/themes/Theme'
import {StyleSheet} from 'react-native'

export const onBoardMentorStyle = () =>
    StyleSheet.create({
        container: {
            backgroundColor: theme.colors.background0,
            flex: 1,
        },
        textInputView: {
            width: SCREEN_WIDTH - 40,
            marginLeft: 15,
        },
        backText: {
            fontSize: 14,
            color: theme.colors.background2,
            marginTop: 10,
            marginLeft: 20,
        },
        textInput: {
            width: '100%',
            fontSize: 16,
            color: theme.colors.textPrimary,
            height: 150,
        },
        centerBtn: {
            height: 44,
            width: 44,
            justifyContent: 'center',
            alignItems: 'center',
        },
        searchWrapper: {
            flexDirection: 'row',
            alignItems: 'center',
            height: 44,
            borderRadius: 20,
            backgroundColor: theme.colors.background0,
            marginLeft: 10,
            marginBottom: 20,
            marginTop: 10,
        },
        text: {
            color: theme.colors.textPrimary,
            marginLeft: 0,
            fontSize: 16,
        },
        actionItemView: {
            overflow: 'hidden',
            borderRadius: 15,
            marginLeft: 10,
            marginTop: 10,
        },
        actionItem: {
            flexDirection: 'row',
            paddingHorizontal: 10,
            alignItems: 'center',
            paddingVertical: 5,
            justifyContent: 'center',
            backgroundColor: theme.colors.background0,
            overflow: 'hidden',
        },
        title: {
            color: theme.colors.textPrimary,
            fontSize: 22,
            width: SCREEN_WIDTH - 40,
            fontWeight: 'bold',
            marginTop: 20,
            textAlign: 'left',
            marginLeft: 20,
        },
        addPhoto: {
            height: 50,
            paddingHorizontal: 10,
            flexDirection: 'row',
            marginTop: 10,
            marginHorizontal: 15,
            borderRadius: 25,
            alignItems: 'center',
            justifyContent: 'center',
        },
        text_desc: {
            fontSize: 16,
            color: theme.colors.textPrimary,
            marginHorizontal: 10,
            marginTop: 0,
        },
        checkedButton: {
            flexDirection: 'row',
            alignItems: 'center',
            height: 50,
            paddingLeft: 5,
            marginTop: 10,
        },
        nonChecked: {
            width: 23,
            height: 23,
            borderRadius: 12,
            borderWidth: 2,
            marginLeft: 10,
            marginRight: 25,
        },
        topImage: {
            width: SCREEN_WIDTH,
            height: 300,
        },
        normalText: {
            fontSize: 16,
            color: theme.colors.textPrimary,
        },
        musicItem: {
            width: (1.5 * SCREEN_WIDTH) / 3,
            height: (1.5 * SCREEN_WIDTH) / 3,
            marginRight: 10,
            borderRadius: 10,
            overflow: 'hidden',
            justifyContent: 'flex-end',
        },
        darkView: {
            width: '100%',
            height: '100%',
            backgroundColor: 'rgba(0,0,0,0.2)',
            position: 'absolute',
            bottom: 0,
        },
        spaceView: {
            width: SCREEN_WIDTH,
            height: 60,
        },
        addhobbieButton: {
            backgroundColor: theme.colors.background2,
            borderRadius: 5,
            flexDirection: 'row',
            width: 130,
            height: 40,
            alignItems: 'center',
            justifyContent: 'space-evenly',
            marginTop: 20,
            marginLeft: 20,
        },
        bodyItem: {
            width: SCREEN_WIDTH,
            height: '100%',
            alignItems: 'center',
        },
        body: {
            width: '100%',
            height: SCREEN_HEIGHT - 100,
            marginTop: 70,
            flexDirection: 'row',
        },
        touchableIcon: {
            width: 40,
            height: 40,
            borderRadius: 40,
            overflow: 'hidden',
            position: 'absolute',
            top: 15,
            left: 15,
        },
        closeIcon: {
            width: 30,
            height: 30,
            borderRadius: 30,
            overflow: 'hidden',
            position: 'absolute',
            top: 10,
            right: 10,
            alignItems: 'center',
            justifyContent: 'center',
        },
        activeSlide: {
            height: '100%',
        },
        linearGradient: {
            width: SCREEN_WIDTH,
            height: 80,
            paddingLeft: 15,
            paddingRight: 15,
            borderRadius: 5,
            position: 'absolute',
            bottom: 0,
        },
        bottomSlide: {
            width: '50%',
            height: 5,
            borderRadius: 50,
            marginTop: 'auto',
            marginLeft: '25%',
            marginBottom: 30,
        },
        plusView: {
            position: 'absolute',
            width: 50,
            height: 50,
            borderRadius: 40,
            bottom: 10,
            right: 15,
            alignItems: 'center',
            justifyContent: 'center',
            elevation: 25,
            overflow: 'hidden',
        },
    })
